title: "Tech and Oncology"
subtitle: // Tech is impacting oncology significantly to improve patient outcomes! //
email: krishna.bala@yahoo.com
description: "The purpose of this blog is to give the readers some insight into technologies that are impacting oncology and patient care!"
# domain: blog.mauromotion.com
#url: https://blog.mauromotion.com
# baseurl: "/thoughts-in-motion"
twitter_username: kbala9702
github_username:  kbala97
#logo: "/assets/images/MauroMotion_logo_v002.png"
github: [metadata]

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt" # "default", "air"contrast", "aqua", "sunrise", "dark", "neon", "plum", "mint"
search: true

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name             : "Krishna Bala, Ph.D."
# avatar           : "assets/images/profile_picture.jpg"
  bio              : "Sr. VP Engineering"
  location         : "New York, NY"
  email            : 
  links:
    # - label: "Email"
    #   icon: "fas fa-envelope"
    #   url: "mailto:krishna.bala@.com"
    # - label: "Portfolio"
    #   icon: "fab fa-behance-square"
    #   url: "https://mauromotion.com"
    # - label: "Mastodon"
    #   icon: "fab fa-mastodon"
    #   url: "https://mograph.social/@mauro"
    - label: "Twitter"
      icon: "fab fa-twitter-square"
      url: "https://twitter.com/kbala9702"
    # - label: "Reddit"
    #   icon: "fab fa-reddit"
    #   url: "https://www.reddit.com/user/mauro_mograph"
    # - label: "Last.fm"
    #   icon: "fab fa-lastfm-square"
    #   url: "https://www.last.fm/user/madmonk_TM_"
    # - label: "Discogs"
    #   icon: "fas fa-record-vinyl"
    #   url: "https://www.discogs.com/user/theRealMadmonk"
      - label: "LinkedIn"
      icon: "fab fa-linkedIn-square"
      url: "https://linkedin.com/kbala97"
    
    
include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true

category_archive:
  type: liquid
  path: /categories/

footer:
  links:
    # - label: "Mastodon"
    #   icon: "fab fa-mastodon"
    #   url: "https://mograph.social/@mauro"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kbala9702"
    - label: "LinkedIn"
      icon: "fab fa-linkedIn-square"
      url: "https://linkedin.com/kbala97"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
